[[local|localrc]]

# Password for everything
ADMIN_PASSWORD=password
DATABASE_PASSWORD=$ADMIN_PASSWORD
RABBIT_PASSWORD=$ADMIN_PASSWORD
SERVICE_PASSWORD=$ADMIN_PASSWORD

# Define the node IP
HOST_IP=127.0.0.1

# Enable Core Services
ENABLED_SERVICES=g-api,g-reg,key,n-api,n-crt,n-obj,n-cpu,n-cond,n-sch,n-novnc,n-api-meta,placement-api,placement-client,q-svc,q-agt,q-dhcp,q-l3,q-meta,neutron,s-proxy,s-object,s-container,s-account

# Logging
LOGFILE=$DEST/logs/stack.sh.log
VERBOSE=True
LOG_COLOR=True
LOGDAYS=1

# Use Neutron instead of Nova-Network
use_neutron=True
